### PR TITLE
Call functions inside module with module.exports

### PR DESCRIPTION
**Pull request by mattiassamskar**
When I use personnummer.format() it throws a `TypeError: Cannot read property 'valid' of undefined` error. I'm not sure why but I suspect is has to do with the scope not being correct. With these code changes it seems to work.
The unit tests also run ok.

### CODE REVIEW

**Comment by frozzare** [comment]
Thanks!

Not sure why is not working. I did another fix that solves this problem without using `module.exports.valid` and that works with `this`

Will create a new release and you are welcome to test the new commit. https://github.com/personnummer/js/commit/8d17aa77c9532df7825c0e8379c29d881ea36b47

**Comment by mattiassamskar** [comment]
👍

**Comment by frozzare** [comment]
@mattiassamskar Released! https://github.com/personnummer/js/releases/tag/v2.0.2

**Comment by mattiassamskar** [comment]
Great! Tested it and works perfectly. Saved me from having to implement format() myself 😅👏

**Pull request closed without merging**
